FROM postgres:17

COPY 01_setup.sql /docker-entrypoint-initdb.d/01_setup.sql
COPY 02_tables.sql /docker-entrypoint-initdb.d/02_tables.sql
COPY 03_seed_data.sql /docker-entrypoint-initdb.d/03_seed.sql

# docker exec -it safeflow-db psql -U postgres -d safeflow_db